import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Menu from '../components/Menu'
import Footer from '../components/Footer';
import Image from 'next/image';
import { Row, Col, Card  } from 'react-bootstrap';
import pepe from '../images/wutface.png';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
      <title>MemH - About</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Menu/>
  
        <div className='contain' >
        <div id='shadowBox'>
          
        <h5 className={styles.title}>
          <b className="gradient-text2">About us</b> <br/>{' '}
          
        </h5>
        </div>
      
            <Row className='padding '>
                <Col>
                    <Card className='p-4 mt-3 bg-white rounded-4 custombtn'>
                        <Card.Title className='fs-1'><b>Chris Mata</b></Card.Title>
                        <Card.Subtitle className="mb-2 text-muted fs-2"><b>ProtocolWhisper</b></Card.Subtitle>
                        <Card.Text className='fs-4'>
                        <b>I love contributing to open source projects. My career interests are contributing in the research and deployment of production solutions that will help web3 scale. Always there to help others and to clarify any doubts.</b>
                        </Card.Text>
                        <Card.Link className='fs-4' href="https://www.linkedin.com/in/chrismatain/">LinkedIn</Card.Link>
                        <Card.Link className='fs-4' href="https://github.com/protocolwhisper">GitHub</Card.Link>
                    </Card>
                </Col>
                <Col>
                    <Card className='p-4 mt-3 bg-white rounded-4 custombtn'>
                        <Card.Title className='fs-1'><b>Joao Freire</b></Card.Title>
                        <Card.Subtitle className="mb-2 text-muted fs-2"><b>JoVi</b></Card.Subtitle>
                        <Card.Text className='fs-4'>
                        <b>Medicine undergrad turned into software developer. Full Stack Developer focused on dApps and blockchain-related software. My main focus is EVM-based chains and EOS/WAX. I love to look for edge-cases.</b>
                        </Card.Text>
                        <Card.Link className='fs-4' href="https://github.com/joaovwfreire">LinkedIn</Card.Link>
                        <Card.Link  className='fs-4'href="https://www.linkedin.com/in/joaovwfreire/">GitHub</Card.Link>
                    </Card>
                </Col>
            </Row>
    
          
        </div>
        <Footer/>
      </main>

     
    </div>
  );
};

export default Home;
