import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Menu from '../components/Menu'
import Footer from '../components/Footer';
import Image from 'next/image';
import { Row, Col, Card, Modal, Button  } from 'react-bootstrap';
import pepe from '../images/wutface.png';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MemH - Collection</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Menu/>
  
        <div className='contain2' >
        <div id='shadowBo'>
          
        <h5 className={styles.title}>
          <b className="gradient-text2">Collection</b> 
          
        </h5>
        </div>
      
        <Card className='containerRight bg-transparent p-3 border-0  collection-card'>
          <Col>
                    <div className='p-3 mt-3 bg-white rounded-4 '>
                       
                        

                        <div className='d-inline-block p-4'>
                        <Card.Title><h3>Welcome to MemH</h3></Card.Title>
                        <Card.Subtitle><h4>A generative collection of memes</h4></Card.Subtitle>
                        <div className='d-flex mt-4'>
                        <div id='img-wrapper'>
                        <Card.Img as={Image}  fluid={true} alt="Card image"  src={pepe}></Card.Img>   
                        </div>
                        <Card.Text><h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h5></Card.Text>
                        </div>
                        </div>
                        
                    </div>
                   
                        
                </Col>

            
          </Card>
    
          
        </div>
        <Footer/>
      </main>

     
    </div>
  );
};

export default Home;
