import type { NextPage } from 'next';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import  PurchaseTokens from '../components/transactions/Mint';
import UserBalance from '../components/UserBalance';
import TotalMints  from '../components/TotalMints';
import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Menu from '../components/Menu'
import Footer from '../components/Footer';
import Image from 'next/image';
import pepe from '../images/wutface.png';
import gift from '../images/gift.png';
import { Row, Col, Card, Modal, Button  } from 'react-bootstrap';

const Home: NextPage = () => {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const [amountToMint, setAmountToMint] = useState(0);
  const addAmount = () => setAmountToMint(amountToMint + 1);
  const subtractAmount = () => {
    if (amountToMint > 0){
      setAmountToMint(amountToMint - 1)
      }
    };


  return (

    <div className={styles.container}>
      <Head>
      <title>MemH - Mint</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Menu/>
  

        <div id='shadowBox'>
          
          <h5 className={styles.title}>
            <b className="gradient-text2">Minting Page</b> <br/>{' '}
            
          </h5>
          </div>        
        <div className='container custombtn2 bg-transparent mb-5' >
          
        <Card className='padding bg-primary custombtn3'>
          
          
            <Image width={2048} height={2048} alt="Card image" src={gift}/>
            
          <Card.Title className='fs-1 p-4 '>Surprise Box</Card.Title>
          <Card.Subtitle className='fs-5 p-4 '>Mint one (or more) of the ∞ unique Memes Against Humanity!</Card.Subtitle>
        
        
          
          </Card>
          <Card className='containerRight bg-transparent p-3 border-0 ' id='bigScreen'>
          <Col>
                    <div className='p-4 mt-3 bg-transparent rounded-4 '>
                        <Card.Title className='fs-1 p-4 '>Surprise Box</Card.Title>
                        <Card.Subtitle className="mb-2 fs-5 px-4 ">Generate a never seen before Meme!</Card.Subtitle>
                        

                        
                        

                        <div className='d-inline-block px-4 text-black fw-bold fs-2'>
                        <UserBalance/>
                        <TotalMints/>
                        <h4 className='text-black mt-3'>Price: 0.0 ETH</h4>
                        <h5 className='text-black mt-3 text-muted'>Available: ∞ <br/></h5>
                        <button className='btn-xxl custombtn4 bg-success  text-white button-positioning' onClick={handleShow}> <b>Mint</b></button>
                      
                        </div>
                        
                    </div>
                   
                        
                </Col>

            
          </Card>
          <Card className='containerRight bg-transparent p-3 border-0 ' id='smallScreen' >
          <Col>
                    <div className='p-4 mt-3 bg-transparent rounded-4 '>
                       
                        

                        <div className='d-inline-block text-black fw-bold fs-4'>
                        <UserBalance/>
                        <TotalMints/>
                        <h4 className='text-black mt-3'>Price: 0.0 ETH</h4>
                        <h5 className='text-black mt-3 text-muted'>Available: ∞ <br/></h5>
                        <button className=' btn-xl custombtn4 bg-success  text-white button-small-positioning ' onClick={handleShow}> <b>Mint</b></button>
                      
                        <Modal className='padding-bottom-btn' show={show} onHide={handleClose}>
                        <PurchaseTokens />
                        </Modal>
                        </div>
                        
                    </div>
                   
                        
                </Col>

            
          </Card>
          
        </div>
          
     
        <Footer/>
      </main>

     
    </div>
  );
};

export default Home;
